version: '3'

services:
  frontend:
    restart: always
    build: ./frontend
    container_name: IG-frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    
  api:
    restart: always
    build: ./api
    container_name: IG-api
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app

  mongo:
    image: mongo
    restart: always
    container_name: IG-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: very-strong-db-password
    volumes:
      - /mnt/volume_nyc1_01/docker_volumes/mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: IG-mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: very-strong-db-password
      ME_CONFIG_MONGODB_URL: mongodb://root:very-strong-db-password@mongo:27017/
    depends_on:
      - mongo

volumes:
  mongodb_data: